# Generated by Django 6.0.2 on 2026-04-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('points', models.IntegerField(default=0)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('initial_stock_per_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('items_count', models.IntegerField(default=1)),
                ('max_stock', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_packaging', models.BooleanField(default=False)),
                ('packaging_type', models.CharField(choices=[('HOT_CUP', 'Hot Cup'), ('COLD_CUP', 'Cold Cup'), ('HOT_STRAW', 'Hot Straw'), ('COLD_STRAW', 'Cold/Frappe Straw'), ('CARRIER', 'Plastic Carrier'), ('HOT_LID', 'Hot Lid'), ('COLD_LID', 'Cold Lid'), ('NONE', 'None')], default='NONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Soft Product', 'Soft Product'), ('Other', 'Other')], default='Coffee', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base Price for SMALL HOT (Tax Inclusive)', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('ice_upcharge', models.DecimalField(decimal_places=2, default=0.25, max_digits=6)),
                ('frappe_upcharge', models.DecimalField(decimal_places=2, default=0.5, max_digits=6)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide from customer menu (Snooze)')),
                ('can_be_hot', models.BooleanField(default=True)),
                ('can_be_iced', models.BooleanField(default=False)),
                ('can_be_frappe', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('service_type', models.CharField(default='Dine-in', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(default='Medium', max_length=20)),
                ('sugar', models.CharField(default='100%', max_length=20)),
                ('product_type', models.CharField(default='Hot', max_length=20)),
                ('price_at_sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_at_sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50)),
                ('attribute_value', models.CharField(max_length=50)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount in g, ml, or pcs', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='sales.product')),
            ],
            options={
                'unique_together': {('product', 'ingredient', 'size')},
            },
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='sales.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('RESTOCK', 'Manual Restock'), ('REDUCTION', 'Order Deduction'), ('ADJUST', 'Manual Adjustment')], default='RESTOCK', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales.ingredient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
