# Generated by Django 6.0.2 on 2026-04-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for Large (Tax Inclusive)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for Medium (Tax Inclusive)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for Small (Tax Inclusive)', max_digits=10),
        ),
    ]
