# Generated by Django 6.0.2 on 2026-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_update_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra charge to the customer', max_digits=10),
        ),
    ]
