# Generated by Django 6.0.2 on 2026-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product_frappe_upcharge_product_ice_upcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='items_count',
            field=models.IntegerField(default=1),
        ),
    ]
