# Generated by Django 6.0.2 on 2026-04-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_product_category_alter_product_image'),
        ('sales', '0003_recipe_extra_price'),
    ]

    operations = [
    ]
