# Generated by Django 6.0.2 on 2026-02-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_ingredient_alter_orderitem_notes_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='min_stock_limit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='sales.product'),
        ),
    ]
