# Generated by Django 6.0.2 on 2026-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_ingredient_items_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='stock_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
