# Generated by Django 6.0.2 on 2026-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_product_category_passwordresetotp_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Soft Drink', 'Soft Drink'), ('Other', 'Other')], default='Coffee', max_length=100),
        ),
    ]
