# Generated by Django 6.0.2 on 2026-04-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_merge_20260423_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_optional',
        ),
    ]
