# Generated by Django 6.0.2 on 2026-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
    ]
