# Generated by Django 6.0.2 on 2026-03-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_ingredient_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='initial_stock_per_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
