# Generated by Django 6.0.2 on 2026-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_ingredient_initial_stock_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_cost',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
