# Generated by Django 6.0.2 on 2026-05-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_points_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
