# Generated by Django 6.0.2 on 2026-05-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_order_cash_change_order_cash_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discount_rate',
        ),
    ]
