# Generated by Django 6.0.2 on 2026-03-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_ingredient_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
