# Generated by Django 6.0.2 on 2026-03-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_ingredient_last_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
