# Generated by Django 6.0.2 on 2026-05-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_customer_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=0, help_text='Daily sequential order number that resets each day and wraps at 1000'),
        ),
    ]
