# Generated by Django 6.0.2 on 2026-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_be_frappe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_hot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_iced',
            field=models.BooleanField(default=False),
        ),
    ]
