# Generated by Django 6.0.2 on 2026-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_recipe_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_packaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='packaging_type',
            field=models.CharField(choices=[('HOT_CUP', 'Hot Cup'), ('COLD_CUP', 'Cold Cup'), ('HOT_STRAW', 'Hot Straw'), ('COLD_STRAW', 'Cold/Frappe Straw'), ('CARRIER', 'Plastic Carrier'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
