# Generated by Django 6.0.2 on 2026-05-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
