# Generated by Django 6.0.2 on 2026-03-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_ingredient_is_packaging_ingredient_packaging_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='max_stock',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
