# Generated by Django 6.0.2 on 2026-03-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_product_can_be_frappe_product_can_be_hot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drink_type',
            field=models.CharField(default='Hot', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sugar',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Matcha', 'Matcha'), ('Other', 'Other')], default='Coffee', max_length=20),
        ),
    ]
