# Generated by Django 6.0.2 on 2026-03-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_ingredient_max_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'ingredient', 'size')},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Amount in g, ml, or pcs', max_digits=10),
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='sales.recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='amount_needed',
        ),
    ]
