# Generated by Django 6.0.2 on 2026-03-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_recipe_unique_together_alter_recipe_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='packaging_type',
            field=models.CharField(choices=[('HOT_CUP', 'Hot Cup'), ('COLD_CUP', 'Cold Cup'), ('HOT_STRAW', 'Hot Straw'), ('COLD_STRAW', 'Cold/Frappe Straw'), ('CARRIER', 'Plastic Carrier'), ('HOT_LID', 'Hot Lid'), ('COLD_LID', 'Cold Lid'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
