# Generated by Django 6.0.2 on 2026-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_ingredient_packaging_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frappe_upcharge',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='ice_upcharge',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=6),
        ),
    ]
