# Generated by Django 6.0.2 on 2026-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_drinkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkrequest',
            name='size',
            field=models.CharField(default='Small', max_length=20),
        ),
    ]
