# Generated by Django 6.0.2 on 2026-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_drinkrequest_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
