# Generated by Django 6.0.2 on 2026-03-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_order_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base Price for SMALL HOT (Tax Inclusive)', max_digits=10),
        ),
    ]
