# Generated by Django 6.0.2 on 2026-03-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_orderitem_is_completed_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from customer menu (Snooze)'),
        ),
    ]
