# Generated by Django 6.0.2 on 2026-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(default='Dine-in', max_length=20),
        ),
    ]
