# Generated by Django 6.0.2 on 2026-03-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_order_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='amount_added',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='type',
            field=models.CharField(choices=[('RESTOCK', 'Manual Restock'), ('REDUCTION', 'Order Deduction'), ('ADJUST', 'Manual Adjustment')], default='RESTOCK', max_length=20),
        ),
    ]
