# Generated by Django 6.0.2 on 2026-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_rename_amount_added_stockhistory_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
