# Generated by Django 6.0.2 on 2026-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_orderitem_cost_at_sale_orderitem_price_at_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Soft Drink', 'Soft Drink'), ('Other', 'Other')], default='Coffee', max_length=20),
        ),
    ]
